SELECT * FROM employee;
SELECT MAX(salary) FROM employee;
SELECT job, MAX(salary) FROM employee GROUP BY job;

SELECT JOB, AVG(SALARY) FROM EMPLOYEE
WHERE JOB = 'CLERK'
GROUP BY JOB;

--WHERE절에는 GROUP불가
SELECT JOB, AVG(SALARY) FROM EMPLOYEE
WHERE AVG(SALARY) >= 3000
GROUP BY JOB;

--GROUP절에는 HAVING이라는 키워드를 써야함
SELECT JOB, AVG(SALARY) FROM EMPLOYEE
GROUP BY JOB
HAVING AVG(SALARY) >= 3000